framework:
  cache:
    app: cache.adapter.redis
    system: cache.adapter.system

    default_redis_provider: '%env(resolve:REDIS_DSN)%'

    pools:
#      mycache.cache:
#        adapter: cache.adapter.redis
#        tags: true
